---
- name: Configure NSX-T
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Create JSON template file for VLAN transport zone
      template: 
        src=../templates/tz_vlan.json
        dest=/tmp/tz_vlan.json
    - name: Create JSON template file for overlay transport zone
      template: 
        src=../templates/tz_overlay.json
        dest=/tmp/tz_overlay.json
    - name: Create JSON template file for Edge VLAN transport zone
      template: 
        src=../templates/tz_edge_vlan.json
        dest=/tmp/tz_edge_vlan.json
    - name: Create JSON template file for host uplink profile
      template: 
        src=../templates/host_uplink_profile.json
        dest=/tmp/host_uplink_profile.json
    - name: Create JSON template file for edge uplink profile
      template: 
        src=../templates/edge_uplink_profile.json
        dest=/tmp/edge_uplink_profile.json
    - name: Create VLAN transport zone
      uri:
        url: "https://{{ nsxman.nsxman01.hostname }}/api/v1/transport-zones/"
        user: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        method: POST
        body: "{{ lookup('file','/tmp/tz_vlan.json') }}"
        force_basic_auth: yes
        status_code: 201
        validate_certs: no
        body_format: json
    - name: Create overlay transport zone
      uri:
        url: "https://{{ nsxman.nsxman01.hostname }}/api/v1/transport-zones/"
        user: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        method: POST
        body: "{{ lookup('file','/tmp/tz_overlay.json') }}"
        force_basic_auth: yes
        status_code: 201
        validate_certs: no
        body_format: json
    - name: Create Edge VLAN transport zone
      uri:
        url: "https://{{ nsxman.nsxman01.hostname }}/api/v1/transport-zones/"
        user: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        method: POST
        body: "{{ lookup('file','/tmp/tz_edge_vlan.json') }}"
        force_basic_auth: yes
        status_code: 201
        validate_certs: no
        body_format: json
    - name: Create host uplink profile
      uri:
        url: "https://{{ nsxman.nsxman01.hostname }}/api/v1/host-switch-profiles/"
        user: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        method: POST
        body: "{{ lookup('file','/tmp/host_uplink_profile.json') }}"
        force_basic_auth: yes
        status_code: 201
        validate_certs: no
        body_format: json
    - name: Create edge uplink profile
      uri:
        url: "https://{{ nsxman.nsxman01.hostname }}/api/v1/host-switch-profiles/"
        user: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        method: POST
        body: "{{ lookup('file','/tmp/edge_uplink_profile.json') }}"
        force_basic_auth: yes
        status_code: 201
        validate_certs: no
        body_format: json

    - name: Fetch NSX Manager API thumnprint
      vmware_vm_shell:
        hostname: "{{ vc_mng.ip }}"
        username: "{{ vc_mng.user }}"
        password: "{{ vc_mng.password }}"
        datacenter: "{{ vc_mng.datacenter }}"
        validate_certs: false
        vm_id: "{{ nsxman.nsxman01.vmname }}"
        vm_username: "{{ nsxmanadminuser }}"
        vm_password: "{{ nsxmanpassword }}"
        vm_shell: get
        vm_shell_args: "certificate api thumbprint"
        wait_for_process: yes
      async: 7200
      poll: 0
      register: thumbprint

    - name: Find temporary JSON templates files
      find:
        path: /tmp
        patterns: "*.json"
      register: files_to_delete
    - name: Delete temporary JSON templates files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"