---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Check if the NSX-T license file exists
      stat: 
        path: "{{ nsxlicense }}"
      register: nsxlicensekey  
    - name: Deploy and configure NSX-T Edge Transport Nodes
      nsxt_transport_nodes:
        hostname: "{{ nsxman.nsxman01.hostname }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        display_name: "{{ item.display_name }}"
        description: "Edge transport node"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{ item.host_switches }}"
        node_deployment_info: "{{ item.node_deployment_info }}"
        state: present
      with_items:
        - "{{ edge_transport_nodes }}"
      ignore_errors: True
      register: _deploy_edges
      when: nsxlicensekey.stat.exists == True
      async: 1800
      poll: 0
    - name: Wait for NSX-T Edge node deployment to finish
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: _jobs
      until: _jobs.finished
      delay: 30
      retries: 10
      with_items: "{{ _deploy_edges.results }}"


