---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Add Edge VM
      nsxt_fabric_nodes:
        hostname: "{{ nsxman.nsxman01.hostname }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        resource_type: "EdgeNode"
        display_name: "{{ item.value.name }}"
        ip_addresses:
        deployment_config:
          form_factor: "{{ item.value.form_factor }}"
          node_user_settings:
            dns_servers: "{{ dns1 }}"
            cli_password: "{{ item.value.password }}"
            root_password: "{{ item.value.password }}"
          vm_deployment_config:
            placement_type: VsphereDeploymentConfig
            vc_name: "{{ vcenter.fqdn }}"
            data_network_ids:
            - "{{ item.value.uplink1_pg }}"
            - "{{ item.value.uplink2_pg }}"
            management_network_id: "{{ item.value.mgmt_pg }}"
            hostname: "{{ item.value.hostname }}"
            compute_id: "{{ item.value.cluster }}"
            host_id: "{{ item.value.esxi_host }}"
            storage_id: "{{ item.value.datastore }}"
            default_gateway_addresses:
            - "{{ item.value.gw }}"
            enable_ssh: True
            management_port_subnets:
            - ip_addresses:
              - "{{ item.value.ip }}"
              prefix_length: "{{ item.value.mask }}"
        #node_settings:
         #   dns_servers: 
          #  - "{{ dns1 }}"
           # search_domains: 
            #- "{{ domain }}"
            #ntp_servers: 
            #- "{{ ntp_server }}"
        state: present
      with_dict: "{{ edge_nodes }}"