---
- name: Move ESXi VMs
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Move the ESXi VMs to folder
      vmware_guest_move:
        hostname: "{{ vc_mng.ip }}"
        username: "{{ vc_mng.user }}"
        password: "{{ vc_mng.password }}"
        datacenter: "{{ vc_mng.datacenter }}"
        validate_certs: no
        name: "{{ item.value.vmname }}"
        dest_folder: "{{ vcfolder }}"
      with_dict: "{{ vESX }}"
      delegate_to: localhost