---
- name: Prepare physical ESXi
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Add a VMware vSwitch to a specific host system
      vmware_vswitch:
        hostname: "{{ physicalESX.host }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        esxi_hostname: "{{ physicalESX.host }}"
        switch_name: "{{ physicalESX.vswitch }}"
        mtu: 9000
    - name: Create management portgroup for the lab environment
      vmware_portgroup:
        hostname: "{{ physicalESX.host }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        esxi_hostname: "{{ physicalESX.host }}"
        switch_name: "{{ physicalESX.vswitch }}"
        portgroup_name: "{{ physicalESX.vlanpg }}"
        vlan_id: "{{ physicalESX.vlan }}"
        network_policy:
          promiscuous_mode: True
        validate_certs: False
    - name: Create trunk port group for the lab environment
      vmware_portgroup:
        hostname: "{{ physicalESX.host }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        esxi_hostname: "{{ physicalESX.host }}"
        switch_name: "{{ physicalESX.vswitch }}"
        portgroup_name: "{{ physicalESX.trunkpg }}"
        vlan_id: "{{ physicalESX.trunkvlan }}"
        network_policy:
          promiscuous_mode: True
          forged_transmits: True
          mac_changes: True
        validate_certs: False

