---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: List IP pools
      nsxt_ip_pools_facts:
        hostname: "{{ nsxman.nsxman01.hostname }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
      check_mode: yes
